security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        main:
            pattern:        ^/
            anonymous:      true
            provider:       app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path:       app_logout
                target:     /
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
    encoders:
        App\Entity\User:
            algorithm:  bcrypt
            cost:       12
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
