version: 2
jobs:
  build:
    docker:
      - image: easybar/php:7.2.9-dev

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: composer install

      - run:
          name: Do tests
          command: make tests
